---
- name: Installation de l'API d'Administration
  hosts: api
  remote_user: root
  connection: local
  vars:
        domain: quchempedia.univ-angers.fr
        repo: https://github.com/younesr19/QuChemPedIA2020.git 
        ansible_python_interpreter: /usr/bin/python3
        api_administration: api_administration
        api_administration_folder: Api_Administration
        user: quchempedia_admin
  roles:
        - utils
        - user
        - nginx
        - flask
